name: 'Update License Year GitHub Action'
description: 'A GitHub Action to update the license year in repositories'
author: 'Eduarda Bastos'

branding:
  icon: 'award'
  color: 'yellow'

inputs:
  github_token:
    description: 'GitHub token to push changes'
    required: true

  branch:
    description: 'Branch to update'
    required: false
    default: ${{ github.ref_name }}

runs:
  using: 'composite'
  steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        ref: ${{ inputs.branch }}

    - name: Update License Year
      run: bash ${{ github.action_path }}/script.sh
      shell: bash
